### ISSUE TITLE
Search bar does not work

### ISSUE THREAD

**Issue by antagomir** [openresearchlabs/openresearchlabs.github.io#16]
In Research -> dropdown selection (e.g. open science) -> the subpage opens, and contains "Search" bar. This does not seem to work as expected (within site) as it is launching full google search. Is it possible convert this easily to limit searches to this website only? If not, perhaps better to remove this Search functionality.

**Comment by tgbd** [comment]
I've tried to fix the search bar with key words, but not succesfully... For now it is commented out

**Comment by antagomir** [comment]
It is ok, I do not think we strictly need this.
