### ISSUE TITLE
Top panel 

### ISSUE THREAD

**Issue by antagomir** [openresearchlabs/openresearchlabs.github.io#25]
Can we have 

- University logo on the top panel positioned to the left
- Turku Data Science Group can be in the middle, or left, whatever looks better
- The menu is perhaps best on the right?

Does not matter too much but I thought these could improve the layout a bit, if easy to implement.

Anyway, if the current one looks better in the end, then we can keep that.

**Comment by tgbd** [comment]
I don't understand what is different from the current version

**Comment by antagomir** [comment]
Ok we can postpone this for now and have a look later over zoom. It looks good already.
