### ISSUE TITLE
Code section

### ISSUE THREAD

**Issue by antagomir** [openresearchlabs/openresearchlabs.github.io#26]
We have a couple of software projects that can be better highlighted at
[http://datascience.utu.fi/code/](http://datascience.utu.fi/code/)

We can keep the current material (I will modify later). But also add boxes linking to the following pages, and showing their logos:

- [miaverse](https://microbiome.github.io)
- [rOpenGov](ropengov.org)
- [Bioconductor](https://www.bioconductor.org/help/search/index.html?q=Leo+Lahti/)
- [COMHIS](https://www2.helsinki.fi/en/researchgroups/computational-history)
- Other: rest of the links on this page to the "Other" box
- Data (with bullet point links to Dryad, Figshare, Github; pick these from the current text)

**Comment by antagomir** [comment]
Could also experiment with horizontal layout for the boxes (project logo on the left, description on the right). Or even without boxes (as long as logo is next to the description). Nice layout more important than whether there are boxes or not.

**Comment by antagomir** [comment]
Looks good already - for the layout I was thinking something similar to [this page](https://bioc2021.bioconductor.org/) so that people images would be replaced with project logos, so we have a horizontal bar for each project, with logo on the left, and description text on the right.

**Comment by tgbd** [comment]
Could you give me the description text for each project please ?

**Comment by antagomir** [comment]
If you just write "Ongoing project" to all those places, I can push the description directly in Git over the weekend?

**Comment by tgbd** [comment]
Sorry, I did not see your response, all you asked is on my branch

**Comment by antagomir** [comment]
I think it would be ok to merge in the master? I can then add my changes in that as I see fit -

**Comment by tgbd** [comment]
It is done

**Comment by antagomir** [comment]
Looks nice! 

Could you still add links to the logos, the links to rOpenGov and COMHIS you can find from the end of the page;
