### ISSUE TITLE
Navigation bar dropdown menus

### ISSUE THREAD

**Issue by antagomir** [openresearchlabs/openresearchlabs.github.io#28]
Are there alternatives for how the navigation bar dropdown menus are shown? Same, but with a visually different impression. We could try out 2-3 alternatives, if it is easy. Then we could see if there is something that looks even nicer. 

This is not a critical feature, and can be omitted because the current version already works well and looks ok. This is just to see if we can improve the visual impression further.

**Comment by tgbd** [comment]
I've tried some other styles, but not very conclusive. Maybe the easier would be for you to tell me exactly with color or styles you would prefer.

**Comment by antagomir** [comment]
It seems that some of us are not that fond of the dropdown menus in the first place. Ok, I am fine with that. 

Let us remove the dropdown menu from the top navigation bar, and instead let us create a landing pages instead. Each navigation bar item takes us to a specific landing page, as we already have for "Team" for instance. For Research and Edu, we can then link to sub pages from that landing page.
