### ISSUE TITLE
Info boxes

### ISSUE THREAD

**Issue by antagomir** [openresearchlabs/openresearchlabs.github.io#39]
reconsider using centered bullet point lists in the info boxes. Bullet points look a bit cheap to me, even a custom icon would be better. It also looks a bit messy when the bullet points are not aligned, although it would look even worse if it was aligned to the left margin.

-> Remove bullet points at least and just keep the text?

It looks lopsided now when there are URLs in some info boxes but not in others. Maybe remove URLs altogether and provide a short description and “Read more”? OR add URLs to all boxes?

-> The boxes could instead point to landing pages - but perhaps it would be easier to just have 2-3 URLs in each box. Will need to consider what works best.

**Comment by tgbd** [comment]
Is it fine if I remove URLs from boxes ? Then the user could just find all the URLs on antother page like [this one](http://datascience.utu.fi/research-topics/) when he clicks on the logo

**Comment by tgbd** [comment]
This would look like that ![image](https://user-images.githubusercontent.com/64830588/124272232-c08f3c80-db3e-11eb-86f4-f69148d6812f.png)

**Comment by antagomir** [comment]
I think it is ok to remove them for now, yes. 

Is it easy to add the links back afterwards if needed? Just adding the links in the box text as normal html?

**Comment by tgbd** [comment]
Yes, it is very easy, I just comment it out
