### ISSUE TITLE
Edu page

### ISSUE THREAD

**Issue by antagomir** [openresearchlabs/openresearchlabs.github.io#51]
Could we have a similar subpage structure in Edu landing page than what we now have in the Research landing page?

Two categories are sufficient:
- Courses and events
- Teaching materials and resources

**Comment by tgbd** [comment]
Yes that is what I've done first. But the page looked empty, as I do not have any text like in Research landing page.

**Comment by antagomir** [comment]
Right, it is ok now to have it mostly empty, I will fill in the gaps with some content when the layout is there.
