### ISSUE TITLE
bibtex automating links

### ISSUE THREAD

**Issue by antagomir** [openresearchlabs/openresearchlabs.github.io#70]
Some of the publications are available online only as PDFs on our website.

For instance,
"Best practices in bibliographic data science" in  the [computational humanities](http://datascience.utu.fi/research/computational-humanities/) subpage.

The corresponding bibtex entry is "Lahti2019rdhum" in ./content/publication/resources/bibtex/lahti.bib

This has the field "pdf" i.e. "pdf = papers/2019-Lahti-RDHUM.pdf" - this refers to
./content/publication/resources/papers/2019-Lahti-RDHUM.pdf

Is there are way to automated the linking of these PDFs in the same as the linking of URLs has been automated (i.e. links rendered in the publication titles on the website view)?

**Comment by antagomir** [comment]
Hmm - - URL seems to be implemented already. 

The task is then either convert "all pdf/paper.pdf" paths to full URLs; or to add automated URL construction from such. 

If the latter is easy to implement it could be handy. But obviously not critical

**Comment by pitkant** [comment]
In principle this is doable but I noticed that csljson does not convert fields such as pdf to json and therefore a discrete URL to a pdf file cannot be read. This could be circumvented by using URL field for storing the path to the pdf file.

However, all URLs should either be absolute or relative, it would be a mess if some URLs were absolute and some URLs were relative.

**Comment by antagomir** [comment]
right. probably just easier to move all URLs absolute then.
