### ISSUE TITLE
Sorting by year for bibs

### ISSUE THREAD

**Issue by antagomir** [openresearchlabs/openresearchlabs.github.io#79]
Is there a chance to get these sorted by year (latest on top):
http://datascience.utu.fi/research/all/

-> And same for the thematic subpages.

**Comment by pitkant** [comment]
While probably not the most optimal solution, I solved this by rearranging the whole lahti.bib file so that newest entries are at the top and oldest entries at the bottom. Then the .json file is also in this order

**Comment by antagomir** [comment]
This is also possible and helps to maintain the file itself. But if there is an easy automated solution it would be good to know. If not easy, no need to spend much more time on searching one.
